    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Bun (Lovable Environment)
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: |
          export TSC_COMPILE_ON_ERROR=true
          export ES_LINT_DISABLE=true
          bun run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
